"\n               I'm a monolithic unix based"
"\n \\_\\_    _/_/  kernel created by"
"\n     \\__/      Rohit Yadav"
"\n     (o0)\\________"
"\n     (#_)\\ TANTRA )\\"
"\n        ||------w |"
"\n        ||       ||\n"
