"               I'm a unix-like                                                  "
" \\_\\_    _/_/  hobby kernel built by                                            "
"     \\__/       bhaisaab!                                                       "
"     (o0)\\________                                                              "
"     (#_)\\ TANTRA )\\                                                            "
"        ||------w |                                                             "
"        ||       ||                                                             "
