#ifndef MULTIBOOT_H
#define MULTIBOOT_H

#define MULTIBOOT_PAGE_ALIGN            (1<<0)
#define MULTIBOOT_MEMORY_INFO           (1<<1)
#define MULTIBOOT_HEADER_MAGIC          (0x1BADB002)
#define MULTIBOOT_BOOTLOADER_MAGIC      (0x2BADB002)
#define MULTIBOOT_HEADER_FLAGS          (MULTIBOOT_MEMORY_INFO | MULTIBOOT_PAGE_ALIGN)
#define CHECKSUM                        (-(MULTIBOOT_HEADER_MAGIC + MULTIBOOT_HEADER_FLAGS))

#endif
