"               I'm a unix-like                                                  "
" \\_\\_    _/_/  hobby kernel built by                                            "
"     \\__/       @rhtyd                                                         "
"     (o0)\\________                                                              "
"     (#_)\\ tantra )\\                                                            "
"        ||------w |                                                             "
"        ||       ||                                                             "
